### ISSUE TITLE
SyntaxError: application.py", line 40

### ISSUE THREAD

**Issue by makayabou** [kibaffo33/aws_transcribe_to_docx#3]
Hello, sorry I couldn't get to use it,
after cloning it,   
then `sudo pip install .`    
 without errors, and then :  
 
```zsh
➜  aws_transcribe_to_docx git:(master) ✗ trdx -f entretienm2-gess.json 
Traceback (most recent call last):
  File "/usr/local/bin/trdx", line 11, in <module>
    load_entry_point('AWS-Transcribe-.json-to-.docx==0.1', 'console_scripts', 'trdx')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/application.py", line 40
    click.echo(f"{click.format_filename(file)} opened...")
                                                        ^
SyntaxError: invalid syntax
``` 
Same thing with python3-pip et python3.5 as default python.

I missed something I guess.  
thank you

**Comment by kibaffo33** [comment]
> python3.5 as default python

The script uses f-strings which are Python 3.7+.

**Comment by kibaffo33** [comment]
README updated https://github.com/kibaffo33/aws_transcribe_to_docx/commit/12fc4e58b6a2e0d1f3cc8599c6c41a5cefebe717
